packages:
  - .

overrides:
  esbuild: ">=0.24.3"
  postcss: ">=8.5.10"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
